In [2]:
#importing numpy#
import numpy as np

In [17]:
hamoye_array = np.array([0,3,5,7,9])

In [21]:
hamoye_array

array([0, 3, 5, 7, 9])

In [22]:
hamoye_array[3]

7

In [24]:
hamoye_array[3:]

array([7, 9])

In [25]:
hamoye_array[:3]

array([0, 3, 5])

In [26]:
hamoye_array[1:3]

array([3, 5])

In [27]:
hamoye_array[3:1]

array([], dtype=int32)

In [28]:
hamoye_array[0:-2]

array([0, 3, 5])

In [3]:
hamoye_a2 = np.array([[0,1,3,5], [2,4,6,8]], float)

In [34]:
hamoye_array.dtype

dtype('int32')

In [35]:
hamoye_array.shape

(5,)

In [4]:
hamoye_a2.shape

(2, 4)

In [36]:
len(hamoye_array)

5

In [37]:
hamoye_array.size

5

In [4]:
hamoye_range = np.array(range(10))

In [39]:
hamoye_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
hamoye_range[2:5]

array([2, 3, 4])

In [42]:
hamoye_range[5:2]

array([], dtype=int32)

In [43]:
hamoye_range.dtype

dtype('int32')

In [45]:
hamoye_range2 = np.array(range(5),float)

In [48]:
hamoye_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
hamoye_range2

array([0., 1., 2., 3., 4.])

In [50]:
hamoye_range2[0:]

array([0., 1., 2., 3., 4.])

In [52]:
hamoye_range2[3:4]

array([3.])

In [62]:
7 in hamoye_range

True

In [63]:
7 in hamoye_range2

False

In [67]:
hamoye_array2 = np.array([[1,3,5,7], [0,2,4,6,8]], float)

ValueError: setting an array element with a sequence.

In [68]:
hamoye_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
hamoye_range[3] = 27

In [70]:
hamoye_range

array([ 0,  1,  2, 27,  4,  5,  6,  7,  8,  9])

In [1]:
len(hamoye_range)

NameError: name 'hamoye_range' is not defined

In [5]:
len(hamoye_range)

10

In [6]:
hamoye_range.shape

(10,)

In [7]:
hamoye_range.dtype

dtype('int32')

In [8]:
hamoye_range.shape

(10,)

In [9]:
hamoye_range.size

10

In [3]:
hamoye_2

NameError: name 'hamoye_2' is not defined

In [4]:
hamoye_a2

array([[0., 1., 3., 5.],
       [2., 4., 6., 8.]])

In [5]:
hamoye_a2[3]

IndexError: index 3 is out of bounds for axis 0 with size 2

In [6]:
import numpy as np

In [7]:
a = [4,5,65]

In [8]:
a

[4, 5, 65]

In [9]:
a.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [10]:
a.type

AttributeError: 'list' object has no attribute 'type'

In [11]:
type(a)

list

In [12]:
np.random.random

<function RandomState.random>

In [13]:
random = np.random.random

random
## Slicing through two-dimensional arrays

In [15]:
practice = np.array([[3,4,34], [8,7, 23]], float)

In [16]:
practice

array([[ 3.,  4., 34.],
       [ 8.,  7., 23.]])

In [5]:
practice2 = np.array([[43,42,2], [75,90,97]], float)

In [18]:
practice + practice2

array([[ 46.,  46.,  36.],
       [ 83.,  97., 120.]])

In [19]:
practice[:2]

array([[ 3.,  4., 34.],
       [ 8.,  7., 23.]])

In [20]:
practice[:1]

array([[ 3.,  4., 34.]])

In [21]:
practice[2:5]

array([], shape=(0, 3), dtype=float64)

In [6]:
practice2 * 2

array([[ 86.,  84.,   4.],
       [150., 180., 194.]])

In [7]:
practice2 ** 2

array([[1.849e+03, 1.764e+03, 4.000e+00],
       [5.625e+03, 8.100e+03, 9.409e+03]])

In [23]:
practice2

array([[43., 42.,  2.],
       [75., 90., 97.]])

In [24]:
practice2[2:]

array([], shape=(0, 3), dtype=float64)

In [25]:
practice2[1, 0:2]

array([75., 90.])

In [26]:
practice2[1, 0:3]

array([75., 90., 97.])

In [27]:
practice2[0, 1:3]

array([42.,  2.])

In [28]:
practice2[2, :1]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [149]:
practice2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [151]:
practice2 = practice2.reshape((2,5))
practice2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
practice2[-1, :1]

array([75.])

In [30]:
practice2[-1, :-1]

array([75., 90.])

In [31]:
practice

array([[ 3.,  4., 34.],
       [ 8.,  7., 23.]])

In [32]:
practice[-1,1:]

array([ 7., 23.])

In [33]:
practice[-1:,1:]

array([[ 7., 23.]])

In [39]:
practice[-1.-1:]

SyntaxError: invalid syntax (<ipython-input-39-b7facca18af1>, line 1)

In [41]:
practice3 = np.array([[1,3,4,5,6], [0,23,34,53,86]], int)

In [42]:
practice3

array([[ 1,  3,  4,  5,  6],
       [ 0, 23, 34, 53, 86]])

In [44]:
practice3[-1:,2:]

array([[34, 53, 86]])

In [45]:
practice3[-1:,-2:]

array([[53, 86]])

In [46]:
practice3[1:,3:]

array([[53, 86]])

In [47]:
practice3.shape

(2, 5)

In [48]:
practice3[-2,-2]

5

In [49]:
practice3[-2:,-2:]

array([[ 5,  6],
       [53, 86]])

In [54]:
practice_range = np.array(range(20), float)
practice_range

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [55]:
practice_range[7] = 45

In [56]:
practice_range

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6., 45.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

# Reshaping Arrays

In [60]:
practice_range = practice_range.reshape(4,5)

In [61]:
practice_range

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6., 45.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [62]:
practice_range.shape

(4, 5)

# Lists

In [63]:
a = np.array([3,4,5,6])

In [64]:
a

array([3, 4, 5, 6])

In [65]:
list(a)

[3, 4, 5, 6]

In [66]:
a

array([3, 4, 5, 6])

In [67]:
a.tolist()

[3, 4, 5, 6]

In [68]:
a

array([3, 4, 5, 6])

In [69]:
a.fill(3)

In [70]:
a

array([3, 3, 3, 3])

In [71]:
b = [1,2,3,4]
array(b)

NameError: name 'array' is not defined

In [72]:
practice2 = np.array(range(10)).reshape(5,2)

In [73]:
practice2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [74]:
practice2.transpose

<function ndarray.transpose>

In [75]:
practice2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [76]:
practice2.transpose()

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [77]:
practice2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [78]:
practice2.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
practice2


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [80]:
practice2.inverse()

AttributeError: 'numpy.ndarray' object has no attribute 'inverse'

## Array Concatenation

In [83]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])



In [84]:
a,b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [87]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [88]:
p = np.array([[10, 12,13], [14,15,16]], float)
q = np.array([[20, 22,23], [24,25,26]], float)

In [89]:
np.concatenate((p,q))

array([[10., 12., 13.],
       [14., 15., 16.],
       [20., 22., 23.],
       [24., 25., 26.]])

In [90]:
np.concatenate((p,q), axis=1)

array([[10., 12., 13., 20., 22., 23.],
       [14., 15., 16., 24., 25., 26.]])

In [91]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.arange(5, dtype = float)

array([0., 1., 2., 3., 4.])

In [94]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [98]:
np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [100]:
np.eye(5, k=1,dtype=float)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

## Array Mathematics

In [101]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [102]:
a+b

array([ 6,  8, 10, 12])

In [103]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [104]:
b*a

array([ 5, 12, 21, 32])

In [105]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [106]:
b/a

array([5.        , 3.        , 2.33333333, 2.        ])

## Python-Numpy Broadcasting

In [107]:
x = np.array([[3,4], [5,4], [22,3]])

In [108]:
y = np.array([2,22])

In [109]:
x + y

array([[ 5, 26],
       [ 7, 26],
       [24, 25]])

In [110]:
z=x+y

In [111]:
z.reshape((2,3), float)

TypeError: 'tuple' object cannot be interpreted as an integer

In [112]:
z.dtype

dtype('int32')

In [113]:
y.dtype

dtype('int32')

In [114]:
z=z.reshape((2,3))

In [115]:
z

array([[ 5, 26,  7],
       [26, 24, 25]])

In [116]:
xsqr(a+b)

NameError: name 'sqr' is not defined

In [118]:
(x+y)^2

array([[ 7, 24],
       [ 5, 24],
       [26, 27]], dtype=int32)

In [119]:
x+y

array([[ 5, 26],
       [ 7, 26],
       [24, 25]])

## Floor, Ceil and Rint
Floor gives the upper integer, Ceil gives the lower integer and Rint rounds up to the nearest integer

In [7]:
numbers = np.array([3.2, 2.54, 9.999, 0.1])

In [126]:
numbers.dtype

dtype('float64')

In [127]:
np.floor(numbers)

array([3., 2., 9., 0.])

In [128]:
np.ceil(numbers)

array([ 4.,  3., 10.,  1.])

In [129]:
np.rint(numbers)

array([ 3.,  3., 10.,  0.])

In [130]:
np.pi

3.141592653589793

In [131]:
np.sqr(numbers)

AttributeError: module 'numpy' has no attribute 'sqr'

## Array Iteration

In [133]:
f = np.array([2,3,4,5], float)

In [134]:
f

array([2., 3., 4., 5.])

In [138]:
for hamoye in f:
    print (hamoye)

2.0
3.0
4.0
5.0


In [147]:
g = np.array([[3.2, 2.54, 9.999, 0.1], [3,2,5,4]], float)

In [146]:
for hamoye in g:
    print(hamoye)

[3.2   2.54  9.999 0.1  ]
[3. 2. 5. 4.]


In [148]:
for (a,b) in g:
    print(a+g)

ValueError: too many values to unpack (expected 2)

In [5]:
import numpy as np

In [6]:
numbers

NameError: name 'numbers' is not defined

In [8]:
numbers

array([3.2  , 2.54 , 9.999, 0.1  ])

In [9]:
np.min(numbers)

0.1

In [10]:
np.max(numbers)

9.999

In [11]:
np.avg(numbers)

AttributeError: module 'numpy' has no attribute 'avg'

In [12]:
np.sum(numbers)

15.839

In [13]:
np.average(numbers)

3.95975

In [2]:
import numpy as np

In [3]:
x = np.linspace(1, 10, 2000)

In [4]:
x

array([ 1.        ,  1.00450225,  1.0090045 , ...,  9.9909955 ,
        9.99549775, 10.        ])

In [5]:
y = np.linspace(1,10)

In [6]:
y

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])